# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :test do
    increment_build_number
    build_app(clean:true, scheme: "Runner",export_method:"enterprise",configuration: "Release",skip_codesigning:true)
    build_app(clean:true, scheme: "RunnerDev",export_method:"enterprise",configuration: "Release",skip_codesigning:true)
    build_app(clean:true, scheme: "RunnerMain",export_method:"enterprise",configuration: "Release",skip_codesigning:true)
    build_app(clean:true, scheme: "RunnerReprod",export_method:"enterprise",configuration: "Release",skip_codesigning:true)
    build_app(clean:true, scheme: "RunnerStagging",export_method:"enterprise",configuration: "Release",skip_codesigning:true)
  end
end
